# Generated by Django 4.1.3 on 2023-03-22 01:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_remove_player_user_player_last_login'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='name',
            new_name='username',
        ),
    ]
