# Generated by Django 4.2 on 2023-04-28 01:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_remove_question_date_question_air_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='valid_links',
        ),
    ]
