# Generated by Django 4.2 on 2023-04-28 01:49

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_remove_question_valid_links'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='valid_links',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=50), default=list, size=3),
        ),
    ]
