# Generated by Django 5.0.4 on 2024-10-25 01:04
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0012_board_questiontile'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='round',
            field=models.CharField(null=True, blank=True),
            preserve_default=False,
        ),
    ]
